version: '2'
services:
 mysql:
  image: mysql:5.7.14
  container_name: mysql
  hostname: mysql
  ports:
   - "3306:3306" 
  network_mode: "bru"
  volumes:
   - /home/mysql:/var/lib/mysql
  environment:
   TZ: Europe/Sofia
  env_file:
   - /home/definitions.env


 bacula:
  image: stanimirvelikov/bacula
  container_name: bacula
  hostname: bacula
  ports:
   - "9101:9101" # bconsole -> dir
   - "9102:9102" # dir -> fd
   - "9103:9103" # dir ->sd
  network_mode: "bru"
  environment:
  # DB_NAME: bacula
  # DB_HOST: mysql
  # DB_USER: root
  # DB_PASS: 1
   TZ: Europe/Sofia
   SMTP_SERVER: smtp
  volumes:
   - /bacula:/bacula
   - /etc/bacula/bacula-dir.conf:/etc/bacula/bacula-dir.conf 
   - /etc/bacula/bacula-sd.conf:/etc/bacula/bacula-sd.conf 
   - /etc/bacula/bconsole.conf:/etc/bacula/bconsole.conf
   - /bacula/:/bacula
   - /etc/bacula/
   - /home/stanimir/
  env_file:
   - /home/definitions.env
       
 bacula-web:
  image: stanimirvelikov/bweb
  container_name: bweb
  hostname: bweb
  network_mode: "bru"
  ports: 
   - "80:80"
   - "9095:9095"
  volumes:
  - /etc/bacula/bconsole.conf:/etc/bacula/bconsole.conf
  - /bacula:/bacula
  - /etc/bacula/
  environment:
   TZ: Europe/Sofia
   DOMAINNAME: "vip-consult.co.uk"
  tty: true
  env_file:
   - /home/definitions.env

 smtp:
  image: vipconsult/smtp
  container_name: smtp
  hostname: smtp
  network_mode: "bru"
  ports: 
   - "25:25"
  environment:
   TZ: Europe/Sofia  
   #ENV_SMTP_INTERVAL: "10"
   DOMAINNAME: "vip-consult.co.uk"
   SMTP_SERVER: "compose_smtp_1"
   SMTP_INTERVAL: "1m"
   SMTP_PROCESSING: "queue_only_load_latch"
   SMTP_remote_max_parallel: "2"
   SMTP_queue_run_max: "5"
   SMTP_timeout_frozen_after: "3h"
