version: '2'
services:
 mysql:
  image: mysql:5.7.14
  container_name: mysql
  hostname: mysql
  ports:
   - "3306:3306" 
  network_mode: "bru"
  volumes:
   - /home/mysql:/var/lib/mysql
  env_file:
   - ./definitions.env

 bacula:
  build: bacula
  container_name: bacula
  hostname: bacula
  ports:
   - "9101:9101" # bconsole -> dir
   - "9102:9102" # dir -> fd
   - "9103:9103" # dir ->sd
  network_mode: "bru"
  volumes:
   - /bacula:/bacula
   - /etc/bacula/bacula-dir.conf:/etc/bacula/bacula-dir.conf 
   - /etc/bacula/bacula-sd.conf:/etc/bacula/bacula-sd.conf 
   - /etc/bacula/bconsole.conf:/etc/bacula/bconsole.conf
   - /etc/bacula:/etc/bacula
  env_file:
   - ./definitions.env
  depends_on: 
  - mysql     

 bweb:
  build: bweb
  container_name: bweb
  hostname: bweb
  network_mode: "bru"
  ports: 
   - "9095:9095"
  volumes:
  - /etc/bacula/bconsole.conf:/etc/bacula/bconsole.conf
  - /bacula:/bacula
  - /etc/bacula/
  env_file:
   - ./definitions.env
  depends_on:
   - mysql
#  entrypoint: bash
#  command: -c "ping google.com"

 smtp:
  image: vipconsult/smtp
  container_name: smtp
  hostname: smtp
  network_mode: "bru"
  ports: 
   - "25:25"
  env_file:
   - ./definitions.env
